'use strict';
const STORIES=[
 {id:'hanuman',title:"Hanuman's mission",subtitle:'Help a brave messenger bring good news.',theme:'Courage',takeaway:'Courage + wise action + seva.',prompt:'Can five children retell one picture each?',summary:'Hanuman meets Rama, crosses the ocean, enters Lanka, finds Sita, and returns to Rama with her message.',scenes:[['meeting','Meets Rama','A mission begins by meeting the person you will help.'],['ocean','Crosses the ocean','Hanuman must cross the water before exploring the island.'],['lanka','Enters Lanka','Look for the city where Hanuman will search.'],['sita','Finds Sita','Inside Lanka, Hanuman finds the person he is looking for.'],['news','Brings Rama news','After finding Sita, Hanuman takes her message back.']]},
 {id:'rama',title:"Rama's journey",subtitle:'Rebuild a journey of friendship and homecoming.',theme:'Teamwork',takeaway:'Big journeys need good friends.',prompt:'Which picture shows teamwork most clearly?',summary:'Rama leaves Ayodhya with Sita and Lakshmana. Later he meets Hanuman, allies build a bridge, he reunites with Sita, and they return to Ayodhya.',scenes:[['forest','Leaves Ayodhya','This journey begins when Rama leaves his home.'],['friend','Meets Hanuman','Rama meets a helpful friend before the journey to Lanka.'],['bridge','Allies build a bridge','The team needs a way across the sea.'],['reunion','Reunites with Sita','Rama and Sita meet again before going home.'],['home','Returns to Ayodhya','The journey ends back at home.']]},
 {id:'bharata',title:"Bharata's promise",subtitle:'Discover how a brother keeps his trust.',theme:'Responsibility',takeaway:'Keep your word. Care for others.',prompt:'Which scene best shows responsibility?',summary:"Bharata returns to Ayodhya, learns Rama is in exile, visits him, receives Rama's sandals, and serves the kingdom on Rama's behalf.",scenes:[['return','Returns to Ayodhya','Bharata first comes home from his visit away.'],['learn','Learns Rama has left','At the palace, Bharata learns what happened.'],['visit','Visits Rama','After hearing the news, Bharata goes to see his brother.'],['sandals','Receives the sandals','Bharata receives a reminder of Rama before returning to serve.'],['serve','Serves for Rama','Bharata keeps his promise by caring for the kingdom.']]},
 {id:'ganesha-race',title:"Ganesha's clever race",subtitle:'Can wisdom beat speed?',theme:'Wisdom',takeaway:'Think deeply before you rush.',prompt:'Why did Ganesha choose a different kind of journey?',summary:'Narada brings a special mango. Shiva and Parvati announce a race around the world. Kartikeya speeds away on his peacock. Ganesha circles his parents and explains that they are his world. Pleased by his wisdom, they give him the mango.',scenes:[['mango','Narada brings a mango','The story starts when a special prize arrives.'],['challenge','A race is announced','Before anyone can race, the challenge must be explained.'],['kartikeya','Kartikeya speeds away','One brother chooses speed and starts travelling.'],['parents','Ganesha circles his parents','Ganesha chooses a different way to think about the world.'],['wisdom','Ganesha explains his idea','The final scene reveals why Ganesha made that unusual choice.']]},
 {id:'ganesha-scribe',title:'Ganesha the scribe',subtitle:'A traditional story about focus and understanding.',theme:'Focus',takeaway:'Good work needs focus, understanding and commitment.',prompt:'What made Ganesha a good partner for a huge task?',summary:'In a popular later tradition, Vyasa asks Ganesha to write the Mahabharata. They agree that Vyasa will keep dictating and Ganesha will understand each verse before writing. One popular retelling says Ganesha uses his tusk when his writing tool fails.',scenes:[['vyasa','Vyasa plans the epic','First, the great work must be planned.'],['ask','Vyasa asks Ganesha','Vyasa needs the right person to write.'],['conditions','They agree on conditions','They agree how they will work before starting.'],['write','Ganesha writes for Vyasa','Now the long work can begin.'],['tusk','Ganesha keeps writing','The last picture shows determination when a writing tool fails.']]}
];

let current=0,order=[],history=[],selected=null,completed=new Set(),dragIndex=null;
const $=id=>document.getElementById(id),story=()=>STORIES[current],ids=()=>story().scenes.map(s=>s[0]);
const scene=id=>story().scenes.find(s=>s[0]===id);
function shuffle(){let a=[...ids()];do{for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}}while(a.every((v,i)=>v===ids()[i]));return a}
function move(from,to){if(from===to)return;history.push([...order]);const [v]=order.splice(from,1);order.splice(to,0,v);selected=null;renderBoard();$('undo-button').disabled=false}
function renderTabs(){$('story-picker').innerHTML=STORIES.map((s,i)=>`<button class="story-tab" type="button" data-i="${i}" aria-current="${i===current}"><span class="tab-number">${String(i+1).padStart(2,'0')}</span>${s.title}<span class="tab-done">${completed.has(s.id)?'✓':''}</span></button>`).join('');$('story-picker').querySelectorAll('button').forEach(b=>b.onclick=()=>load(+b.dataset.i,false))}
function renderProgress(){$('progress-count').textContent=`${completed.size} / ${STORIES.length}`;$('progress-dots').innerHTML=STORIES.map(s=>`<i class="${completed.has(s.id)?'done':''}"></i>`).join('')}
function renderBoard(){const words=['FIRST','THEN','THEN','THEN','LAST'];$('story-board').innerHTML=order.map((id,i)=>{const s=scene(id),letter=String.fromCharCode(65+i);return `<li class="scene-slot" data-i="${i}"><button class="position-button" type="button" data-pos="${i}"><span class="position-number">${i+1}</span><span class="position-word">${words[i]}</span></button><article class="scene-card ${selected===i?'selected':''}" draggable="true" data-drag="${i}"><button class="card-select" type="button" data-select="${i}" aria-label="Select ${s[1]}"><div class="card-art"><span class="card-letter">${letter}</span>${window.StoryArt(id)}</div><span class="card-caption">${s[1]}</span></button><div class="card-tools"><button class="move-button" data-left="${i}" ${i===0?'disabled':''} aria-label="Move ${s[1]} left">←</button><button class="drag-handle" type="button" aria-label="Drag ${s[1]}">⠿</button><button class="move-button" data-right="${i}" ${i===4?'disabled':''} aria-label="Move ${s[1]} right">→</button></div></article></li>`}).join('');
 $('story-board').querySelectorAll('[data-select]').forEach(b=>b.onclick=()=>{const i=+b.dataset.select;if(selected===null){selected=i;renderBoard()}else move(selected,i)});
 $('story-board').querySelectorAll('[data-pos]').forEach(b=>b.onclick=()=>{if(selected!==null)move(selected,+b.dataset.pos)});
 $('story-board').querySelectorAll('[data-left]').forEach(b=>b.onclick=e=>{e.stopPropagation();const i=+b.dataset.left;if(i>0)move(i,i-1)});
 $('story-board').querySelectorAll('[data-right]').forEach(b=>b.onclick=e=>{e.stopPropagation();const i=+b.dataset.right;if(i<4)move(i,i+1)});
 $('story-board').querySelectorAll('.scene-card').forEach(c=>{c.ondragstart=e=>{dragIndex=+c.dataset.drag;c.classList.add('dragging');e.dataTransfer.effectAllowed='move'};c.ondragend=()=>{dragIndex=null;c.classList.remove('dragging');document.querySelectorAll('.drop-target').forEach(x=>x.classList.remove('drop-target'))}});
 $('story-board').querySelectorAll('.scene-slot').forEach(slot=>{slot.ondragover=e=>{e.preventDefault();slot.classList.add('drop-target')};slot.ondragleave=()=>slot.classList.remove('drop-target');slot.ondrop=e=>{e.preventDefault();slot.classList.remove('drop-target');if(dragIndex!==null)move(dragIndex,+slot.dataset.i)}})
}
function load(i,mix=true){current=i;history=[];selected=null;order=mix?shuffle():[...ids()];$('round-label').textContent=`STORY ${i+1} OF ${STORIES.length} / ${story().theme}`;$('story-title').textContent=story().title;$('story-subtitle').textContent=story().subtitle;$('feedback').className='feedback';$('feedback').textContent='Five pictures. One story. Build it together!';$('celebration').hidden=true;$('undo-button').disabled=true;renderTabs();renderBoard();renderProgress()}
$('check-button').onclick=()=>{const correct=ids();if(order.every((v,i)=>v===correct[i])){completed.add(story().id);$('feedback').className='feedback success';$('feedback').textContent='Yes — every scene is in the right place.';$('takeaway').textContent=story().takeaway;$('retell-prompt').textContent=story().prompt;$('story-summary').textContent=story().summary;$('celebration').hidden=false;renderTabs();renderProgress();document.querySelectorAll('.scene-card').forEach(x=>x.classList.add('correct'))}else{const n=order.filter((v,i)=>v===correct[i]).length;$('feedback').className='feedback';$('feedback').textContent=`${n} of 5 pictures are already in the right place. Keep building!`;document.querySelectorAll('.scene-card').forEach((x,i)=>x.classList.toggle('needs-move',order[i]!==correct[i]))}}
$('hint-button').onclick=()=>{const correct=ids(),i=order.findIndex((v,j)=>v!==correct[j]);$('feedback').className='feedback hint';$('feedback').textContent=i<0?'Everything is already in place!':scene(correct[i])[2]};
$('undo-button').onclick=()=>{if(history.length){order=history.pop();selected=null;renderBoard();$('undo-button').disabled=!history.length}};
$('shuffle-button').onclick=()=>{history.push([...order]);order=shuffle();selected=null;renderBoard();$('undo-button').disabled=false;$('celebration').hidden=true};
$('next-button').onclick=()=>load((current+1)%STORIES.length,true);
$('zoom-button').onclick=()=>{document.body.classList.toggle('zoom-mode');const on=document.body.classList.contains('zoom-mode');$('zoom-button').setAttribute('aria-pressed',on);$('zoom-button').textContent=on?'Exit Zoom view':'Zoom view'};
document.addEventListener('keydown',e=>{if(selected===null)return;if(e.key==='ArrowLeft'&&selected>0){e.preventDefault();move(selected,selected-1)}if(e.key==='ArrowRight'&&selected<4){e.preventDefault();move(selected,selected+1)}});
load(0,true);
